//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConaxSMS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConaxSMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /************************* Begin Log Entry *************************/.
        /// </summary>
        internal static string BeginLogEntry {
            get {
                return ResourceManager.GetString("BeginLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate not found, please install certificate or check app.config for certificate serial. .
        /// </summary>
        internal static string CertificateNotFoundDesc {
            get {
                return ResourceManager.GetString("CertificateNotFoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will pause for many hours. Please do not close this application and let it run till it finish. Or click cancel to send message NOW. .
        /// </summary>
        internal static string DelayMsg {
            get {
                return ResourceManager.GetString("DelayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /************************* End Log Entry *************************/.
        /// </summary>
        internal static string EndLogEntry {
            get {
                return ResourceManager.GetString("EndLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in adding client certificate in web request..
        /// </summary>
        internal static string ErrAddingCer {
            get {
                return ResourceManager.GetString("ErrAddingCer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message to STB failed. Please check error log. .
        /// </summary>
        internal static string ErrorResponse {
            get {
                return ResourceManager.GetString("ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either message length is too long or message length configuration is not correct. .
        /// </summary>
        internal static string MessageLenError {
            get {
                return ResourceManager.GetString("MessageLenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgLength.
        /// </summary>
        internal static string MsgLenCfgKey {
            get {
                return ResourceManager.GetString("MsgLenCfgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NamespaceURI.
        /// </summary>
        internal static string NsURICfgKey {
            get {
                return ResourceManager.GetString("NsURICfgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in processing response XML. .
        /// </summary>
        internal static string RespXMLErr {
            get {
                return ResourceManager.GetString("RespXMLErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ns2:Message&gt;.
        /// </summary>
        internal static string ReturnMsgClose {
            get {
                return ResourceManager.GetString("ReturnMsgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ns2:Message&gt;.
        /// </summary>
        internal static string ReturnMsgOpen {
            get {
                return ResourceManager.GetString("ReturnMsgOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOAPAction.
        /// </summary>
        internal static string SoapActionVerb {
            get {
                return ResourceManager.GetString("SoapActionVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\nResponse by response stream reader\r\n.
        /// </summary>
        internal static string StreamLogHead {
            get {
                return ResourceManager.GetString("StreamLogHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Conax SMS application.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
